#!/usr/bin/env bash
#
# <xbar.title>mactemp</xbar.title>
# <xbar.version>v1.0</xbar.version>
# <xbar.author>Kenji Tubera</xbar.author>
# <xbar.author.github>kenjichristopherv-del</xbar.author.github>
# <xbar.desc>Apple Silicon thermals: die/SSD/battery temperature plus macOS thermal pressure, and the process causing it. No sudo, no helper daemon, no third-party dependencies.</xbar.desc>
# <xbar.dependencies>swift</xbar.dependencies>
# <xbar.abouturl>https://github.com/kenjichristopherv-del/mactemp</xbar.abouturl>
#
# <xbar.var>number(VAR_ALERT_MINUTES=5): Minutes of sustained trouble before alerting.</xbar.var>
# <xbar.var>number(VAR_BATTERY_WARN=45): Battery temperature (C) treated as too hot.</xbar.var>
# <xbar.var>string(VAR_NOTIFY="both"): Banner delivery — swiftbar, osascript, both, or none.</xbar.var>
#
# Reads real hardware sensors through IOKit's HID event system. The sensor
# reader is Swift, embedded below, compiled once into ~/Library/Caches on first
# run and reused after that. Apple Silicon only.
#
# DO NOT EDIT THIS FILE — it is generated by dist.sh from mactemp.swift and
# plugin.template.sh. Edit those and re-run ./dist.sh.

set -u

CACHE="$HOME/Library/Caches/mactemp"
SRC_HASH="7e9f8bbc7b45"
BIN="$CACHE/mactemp-$SRC_HASH"
STATE="$CACHE/state"
BUILDING="$CACHE/building"
FAILED="$CACHE/build-failed"
mkdir -p "$CACHE"

# --- settings -----------------------------------------------------------------
# A fanless Mac is *designed* to run hot and clamp its own clocks, so temperature
# alone is not a warning signal. Sustained thermal pressure is, because that is
# macOS saying it is actively giving up speed.
#
# Thresholds are measured in elapsed seconds rather than sample counts, so
# changing the refresh rate in the filename does not silently change them.
ALERT_MINUTES="${VAR_ALERT_MINUTES:-5}"
BATTERY_WARN="${VAR_BATTERY_WARN:-45}"
ALERT_SECONDS=$(( ALERT_MINUTES * 60 ))
NOTIFY_COOLDOWN=1800   # seconds between repeat banners

# Banner notifications need a permission macOS may not have granted, and a
# plugin cannot detect delivery failure. They are therefore the *secondary*
# channel — the menubar title always shouts, and that needs no permission.
#   swiftbar  - SwiftBar's own banner    osascript - via Script Editor
#   both | none
NOTIFY_METHOD="${VAR_NOTIFY:-both}"

render_bar() { echo "$1"; echo "---"; shift; printf '%s\n' "$@"; exit 0; }
# Something is wrong and needs attention.
die() { render_bar "thermals ⚠️ | sfimage=thermometer.medium color=#ff6b6b" "$@"; }
# Working as intended, just not ready yet — must not look like a fault.
busy() { render_bar "thermals… | sfimage=thermometer.medium color=#8e8e93" "$@"; }

if [ "$(uname -m)" != "arm64" ]; then
  die "Apple Silicon only" "This plugin reads Apple Silicon SoC sensors, which Intel Macs do not expose."
fi

# --- build on first run -------------------------------------------------------
# Compiling takes a few seconds, and a plugin blocking the menubar that long
# looks like a hang. So the build is detached and the menubar says what it is
# doing; the next refresh picks up the finished binary.
age_of() { # file -> seconds since mtime, or a huge number if absent
  [ -f "$1" ] || { echo 999999; return; }
  echo $(( $(date +%s) - $(stat -f %m "$1" 2>/dev/null || echo 0) ))
}

if [ ! -x "$BIN" ]; then
  if ! command -v swiftc >/dev/null 2>&1; then
    die "Swift compiler not found" "mactemp needs the Command Line Tools." \
        "Install them | bash=/usr/bin/xcode-select param1=--install terminal=true"
  fi

  # A build already running: say so, unless the lock is stale.
  if [ -f "$BUILDING" ]; then
    if [ "$(age_of "$BUILDING")" -lt 300 ]; then
      busy "Building sensor reader…" "First run only. This takes a few seconds." \
           "Check again | refresh=true"
    fi
    rm -f "$BUILDING"
  fi

  # A recent failure: don't retry on every refresh.
  if [ -f "$FAILED" ] && [ "$(age_of "$FAILED")" -lt 600 ]; then
    die "Sensor reader failed to build" "Retrying is paused for 10 minutes." \
        "Show build log | bash=/bin/cat param1='$CACHE/build.log' terminal=true" \
        "Retry now | bash=/bin/rm param1='$FAILED' terminal=false refresh=true"
  fi

  cat > "$CACHE/mactemp.swift" <<'SWIFT_SOURCE_EOF'
// mactemp — read Apple Silicon thermal sensors without sudo.
//
// Sensors come from IOKit's HID event system, the same source Activity Monitor
// and third-party tools use. The symbols are private, so they are resolved at
// runtime with dlsym rather than linked against.

import Foundation
import IOKit

private typealias ClientCreate = @convention(c) (CFAllocator?) -> Unmanaged<AnyObject>?
private typealias ClientSetMatching = @convention(c) (AnyObject?, CFDictionary?) -> Int32
private typealias ClientCopyServices = @convention(c) (AnyObject?) -> CFArray?
private typealias ServiceCopyProperty = @convention(c) (AnyObject?, CFString) -> CFTypeRef?
private typealias ServiceCopyEvent = @convention(c) (AnyObject?, Int64, Int32, Int64) -> AnyObject?
private typealias EventGetFloatValue = @convention(c) (AnyObject?, Int32) -> Double

// kIOHIDEventTypeTemperature. The value field is the type shifted into the
// high half of the field id.
private let temperatureEvent: Int64 = 15
private let temperatureField = Int32(15 << 16)

// PrimaryUsagePage 0xff00 / PrimaryUsage 5 selects temperature sensors only.
private let sensorUsagePage = 0xff00
private let sensorUsage = 5

struct Reading {
    let name: String
    let celsius: Double
}

func readSensors() -> [Reading] {
    guard let iokit = dlopen("/System/Library/Frameworks/IOKit.framework/IOKit", RTLD_NOW) else {
        return []
    }
    func symbol<T>(_ name: String) -> T? {
        guard let p = dlsym(iokit, name) else { return nil }
        return unsafeBitCast(p, to: T.self)
    }
    guard
        let create: ClientCreate = symbol("IOHIDEventSystemClientCreate"),
        let setMatching: ClientSetMatching = symbol("IOHIDEventSystemClientSetMatching"),
        let copyServices: ClientCopyServices = symbol("IOHIDEventSystemClientCopyServices"),
        let copyProperty: ServiceCopyProperty = symbol("IOHIDServiceClientCopyProperty"),
        let copyEvent: ServiceCopyEvent = symbol("IOHIDServiceClientCopyEvent"),
        let floatValue: EventGetFloatValue = symbol("IOHIDEventGetFloatValue"),
        let client = create(kCFAllocatorDefault)?.takeRetainedValue()
    else { return [] }

    let match: [String: Any] = ["PrimaryUsagePage": sensorUsagePage, "PrimaryUsage": sensorUsage]
    _ = setMatching(client, match as CFDictionary)
    guard let services = copyServices(client) as? [AnyObject] else { return [] }

    return services.compactMap { service in
        guard
            let name = copyProperty(service, "Product" as CFString) as? String,
            let event = copyEvent(service, temperatureEvent, 0, 0)
        else { return nil }
        let value = floatValue(event, temperatureField)
        // Unpopulated sensors report small negatives; nothing in this machine
        // legitimately reads below freezing or above 130 C.
        guard value > 0, value < 130 else { return nil }
        return Reading(name: name, celsius: value)
    }
}

func mean(_ xs: [Double]) -> Double? {
    guard !xs.isEmpty else { return nil }
    return xs.reduce(0, +) / Double(xs.count)
}

// "PMU tdie3" / "PMU2 tdie7" are the SoC die sensors — the number that matters.
// The "tdev" siblings track the surrounding board and run cooler and noisier.
let readings = readSensors()
let die = readings.filter { $0.name.contains("tdie") }.map(\.celsius)
let battery = readings.filter { $0.name.lowercased().contains("battery") }.map(\.celsius)
let storage = readings.filter { $0.name.contains("NAND") }.map(\.celsius)

let thermalState: String
switch ProcessInfo.processInfo.thermalState {
case .nominal:  thermalState = "nominal"
case .fair:     thermalState = "fair"
case .serious:  thermalState = "serious"
case .critical: thermalState = "critical"
@unknown default: thermalState = "unknown"
}

func field(_ key: String, _ value: Double?) -> String? {
    guard let value else { return nil }
    return "\"\(key)\":\(String(format: "%.1f", value))"
}

if CommandLine.arguments.contains("--list") {
    for r in readings.sorted(by: { $0.name < $1.name }) {
        let label = r.name.padding(toLength: max(24, r.name.count), withPad: " ", startingAt: 0)
        print("\(label) \(String(format: "%6.2f", r.celsius)) C")
    }
    exit(0)
}

let fields = [
    field("die_max", die.max()),
    field("die_avg", mean(die)),
    field("battery", mean(battery)),
    field("storage", storage.max()),
    "\"thermal_state\":\"\(thermalState)\"",
    "\"sensors\":\(readings.count)",
].compactMap { $0 }

print("{\(fields.joined(separator: ","))}")
SWIFT_SOURCE_EOF

  : > "$BUILDING"
  # Build to a temp name and move into place, so a half-written binary is never
  # executable. Stale builds from older versions are swept on success.
  nohup /bin/bash -c "
    if swiftc -O '$CACHE/mactemp.swift' -o '$BIN.tmp' > '$CACHE/build.log' 2>&1; then
      mv -f '$BIN.tmp' '$BIN'
      rm -f '$FAILED'
      find '$CACHE' -maxdepth 1 -name 'mactemp-*' ! -name 'mactemp-$SRC_HASH' -delete 2>/dev/null
    else
      rm -f '$BIN.tmp'
      touch '$FAILED'
    fi
    rm -f '$BUILDING'
  " >/dev/null 2>&1 &

  busy "Building sensor reader…" "First run only. This takes a few seconds." \
       "Check again | refresh=true"
fi

JSON="$("$BIN" 2>/dev/null)"
[ -z "$JSON" ] && die "No sensor data returned"

field() { echo "$JSON" | sed -n "s/.*\"$1\":\([0-9.]*\).*/\1/p"; }
DIE_MAX="$(field die_max)"
DIE_AVG="$(field die_avg)"
BATTERY="$(field battery)"
STORAGE="$(field storage)"
SENSORS="$(field sensors)"
STATE_NAME="$(echo "$JSON" | sed -n 's/.*"thermal_state":"\([a-z]*\)".*/\1/p')"

# --- how long has it been like this? -----------------------------------------
# Timestamps, not counters: 0 means "not currently in this condition", otherwise
# it is when the condition began.
PRESSURE_SINCE=0; BATTERY_SINCE=0; LAST_NOTIFY=0
# shellcheck disable=SC1090
[ -f "$STATE" ] && . "$STATE"
NOW="$(date +%s)"

case "$STATE_NAME" in
  serious|critical) [ "$PRESSURE_SINCE" -eq 0 ] && PRESSURE_SINCE="$NOW" ;;
  *)                PRESSURE_SINCE=0 ;;
esac

if [ -n "$BATTERY" ] && [ "${BATTERY%.*}" -ge "$BATTERY_WARN" ] 2>/dev/null; then
  [ "$BATTERY_SINCE" -eq 0 ] && BATTERY_SINCE="$NOW"
else
  BATTERY_SINCE=0
fi

held_for() { # since -> seconds held, 0 if not currently held
  [ "$1" -eq 0 ] && { echo 0; return; }
  echo $(( NOW - $1 ))
}
PRESSURE_HELD="$(held_for "$PRESSURE_SINCE")"
BATTERY_HELD="$(held_for "$BATTERY_SINCE")"

pressure_alert() { [ "$PRESSURE_SINCE" -ne 0 ] && [ "$PRESSURE_HELD" -ge "$ALERT_SECONDS" ]; }
battery_alert()  { [ "$BATTERY_SINCE"  -ne 0 ] && [ "$BATTERY_HELD"  -ge "$ALERT_SECONDS" ]; }

PLUGIN="$(basename "$0")"   # SwiftBar's plugin id is the full filename

notify() { # title, body
  local title="$1" body="$2"
  case "$NOTIFY_METHOD" in
    swiftbar|both)
      open "swiftbar://notify?plugin=${PLUGIN}&title=${title// /%20}&body=${body// /%20}" 2>/dev/null ;;
  esac
  case "$NOTIFY_METHOD" in
    osascript|both)
      osascript -e "display notification \"$body\" with title \"$title\"" >/dev/null 2>&1 ;;
  esac
  LAST_NOTIFY="$NOW"
}

if [ $((NOW - LAST_NOTIFY)) -ge "$NOTIFY_COOLDOWN" ]; then
  if pressure_alert; then
    notify "Mac is throttling" "Sustained thermal pressure - expect things to feel slow. Check what is running."
  elif battery_alert; then
    notify "Battery is running hot" "${BATTERY}C sustained. Unplug or move it off soft surfaces."
  fi
fi

printf 'PRESSURE_SINCE=%s\nBATTERY_SINCE=%s\nLAST_NOTIFY=%s\n' \
  "$PRESSURE_SINCE" "$BATTERY_SINCE" "$LAST_NOTIFY" > "$STATE"

# --- what the number means ----------------------------------------------------
# Apple publishes no Tjmax, so these bands come from measured behaviour on
# Apple Silicon: idle sits in the 30s, ordinary work in the 50s-60s, sustained
# load in the 70s-80s, and throttling begins around 95-100. A fanless M3 Air has
# been measured peaking at 114 on the hottest core and settling near 100 once
# throttling engages — so a high number alone is not a fault.
describe_temp() { # integer celsius
  if   [ "$1" -lt 46 ]; then echo "Idle-cool. Nothing is working hard."
  elif [ "$1" -lt 71 ]; then echo "Normal working range."
  elif [ "$1" -lt 91 ]; then echo "Heavy load — expected, and safe by design."
  elif [ "$1" -lt 100 ]; then echo "Very hot, near the throttle point. Still within design limits."
  else echo "At the throttle ceiling. The chip is protecting itself."
  fi
}

# --- render -------------------------------------------------------------------
case "$STATE_NAME" in
  nominal)  COLOR=""; ICON="thermometer.low";    PLAIN="Running free. No clocks are being held back." ;;
  fair)     COLOR=""; ICON="thermometer.medium"; PLAIN="Warm and working. Full speed, nothing to do." ;;
  serious)  COLOR="color=#ff9f0a"; ICON="thermometer.high"; PLAIN="Throttling. Speed is being clamped to shed heat." ;;
  critical) COLOR="color=#ff453a"; ICON="thermometer.high"; PLAIN="Heavily throttled. macOS is aggressively cutting speed." ;;
  *)        COLOR=""; ICON="thermometer.medium"; PLAIN="Thermal state unavailable." ;;
esac

# The always-works alert channel: once something has been wrong long enough to
# be worth saying, the menubar stops being a quiet number and says it in words.
LABEL="${DIE_MAX:+${DIE_MAX%.*}°}"
LABEL="${LABEL:-${STATE_NAME:-thermals}}"
if pressure_alert; then
  echo "$LABEL throttling | sfimage=thermometer.high color=#ff453a"
elif battery_alert; then
  echo "$LABEL battery hot | sfimage=thermometer.high color=#ff9f0a"
else
  echo "$LABEL | sfimage=$ICON $COLOR"
fi
echo "---"
echo "Thermal pressure: ${STATE_NAME:-unknown} | sfimage=$ICON $COLOR"
echo "$PLAIN | size=11 color=#8e8e93"
[ "$PRESSURE_SINCE" -ne 0 ] && echo "Held for $((PRESSURE_HELD / 60))m $((PRESSURE_HELD % 60))s | size=11 color=#8e8e93"
echo "---"
if [ -n "$DIE_MAX" ]; then
  echo "SoC die (hottest)  ${DIE_MAX}°C | font=Menlo size=12"
  echo "SoC die (average)  ${DIE_AVG}°C | font=Menlo size=12"
  echo "$(describe_temp "${DIE_MAX%.*}") | size=11 color=#8e8e93"
else
  echo "No SoC die sensors exposed on this Mac | size=11 color=#8e8e93"
fi
[ -n "$STORAGE" ] && echo "SSD                ${STORAGE}°C | font=Menlo size=12"
if [ -n "$BATTERY" ]; then
  BCOL=""
  [ "${BATTERY%.*}" -ge "$BATTERY_WARN" ] 2>/dev/null && BCOL="color=#ff9f0a"
  echo "Battery            ${BATTERY}°C | font=Menlo size=12 $BCOL"
fi
# --- what to do about it ------------------------------------------------------
# Shown only when there is genuinely something to act on, and tailored to the
# actual condition rather than printing a generic checklist every refresh.
HOT_DIE=0
[ -n "$DIE_MAX" ] && [ "${DIE_MAX%.*}" -ge 91 ] 2>/dev/null && HOT_DIE=1
if [ "$STATE_NAME" = "serious" ] || [ "$STATE_NAME" = "critical" ] ||
   [ "$HOT_DIE" -eq 1 ] || [ "$BATTERY_SINCE" -ne 0 ]; then
  echo "---"
  echo "What to do"
  echo "Quit the top process below if you don't need it | size=11"
  echo "Get it off fabric — the chassis is the heatsink | size=11"
  if pmset -g batt 2>/dev/null | grep -q "AC Power"; then
    echo "Unplug if you can — charging adds its own heat | size=11"
  fi
  echo "Rooms above 35°C are outside Apple's spec | size=11"
  echo "None of this risks damage — the chip throttles to protect itself | size=11 color=#8e8e93"
fi
echo "---"
echo "Top CPU right now"
ps -Ao %cpu,comm -r 2>/dev/null | sed -n '2,4p' | while read -r pct cmd; do
  echo "$(printf '%5s%%' "$pct")  $(basename "$cmd") | font=Menlo size=12"
done
echo "---"
echo "Open Activity Monitor | bash=/usr/bin/open param1=-a param2='Activity Monitor' terminal=false"
echo "All ${SENSORS:-0} sensors | bash='$BIN' param1=--list terminal=true"
echo "Refresh | refresh=true"
